name: sprawozdanie

on: push # kod się wykona przy wykonaniu push'a
jobs:
    job:
        runs-on: ubuntu-22.04 # na czym ma działać
        steps:
            - run: sudo apt-get install inkscape pandoc texlive-xetex
            - uses: actions/checkout@v4
            - run: pip install ipykernel nbconvert pint open-atmos-jupyter-utils scipy matplotlib
            - run: python -m nbconvert --to pdf --execute main.ipynb
            - uses: actions/upload-artifact@v4
              with:
                  path: main.pdf
